//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

         
// USER INCLUDES			
#include <SI_EFM8BB3_Register_Enums.h>

//-----------------------------------------------------------------------------
// Global VARIABLES
//-----------------------------------------------------------------------------
int LEDCOUNT = 0;
int maxLen=10;
//-----------------------------------------------------------------------------
// Global CONSTANTS
//-----------------------------------------------------------------------------
SI_SBIT(LED0, SFR_P1, 7);                  // P1.4 LED0
SI_SBIT(LED1, SFR_P1, 5);                  // P1.5 LED1
SI_SBIT(LED2, SFR_P1, 6);                  // P1.6 LED2

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN::TF2L (Timer # Low Byte Overflow Flag)
//
// This routine changes the state of the LED whenever Timer2 overflows.
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
{
	TMR2CN0_TF2H = 0;                  // Clear Timer2 interrupt flag
	if (LEDCOUNT==0){
		P0_B7=0;
	}
	else if (LEDCOUNT==maxLen/2){
		P0_B7=1;
	}

	if (LEDCOUNT>maxLen){
		LEDCOUNT=0;
	}
	else {
		LEDCOUNT++;
	}

//	switch (LEDCOUNT)
//	{
//		case 0:
//		   P0_B7=0;
//		   break;
//		case maxLen/2:
//		   P0_B7 = 1;
//		   break;
//	}
//
//	if (LEDCOUNT <= maxLen) LEDCOUNT++;
//	else LEDCOUNT = 0;
}

SI_INTERRUPT (PMATCH_ISR, PMATCH_IRQn){

	if (P0_B2==0){
		maxLen+=2;
		if (maxLen>160){
			maxLen=160;
		}
	}
	if (P0_B3==0){
		maxLen-=2;
		if (maxLen<0){
			maxLen=0;
		}
	}
	SFRPAGE=LEGACY_PAGE;
	EIE1 &= ~0x02;
}


